/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ru.clevertec;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertTrue;

class AppTest {
    @Test void appHasAGreeting() {
        assertTrue(true, "app should have a greeting");
    }
}
